export const seedMembers = [
  {
    id: 'm1',
    name: 'Nguyễn Văn A',
    gender: 'male',
    birthDate: '1945-01-01',
    deathDate: '',
    occupation: 'Nông dân',
    bio: 'Ông tổ của dòng họ.',
    photo: '',
    parentIds: [],
    spouseIds: ['m2'],
  },
  {
    id: 'm2',
    name: 'Trần Thị B',
    gender: 'female',
    birthDate: '1948-03-12',
    deathDate: '',
    occupation: '',
    bio: '',
    photo: '',
    parentIds: [],
    spouseIds: ['m1'],
  },
  {
    id: 'm3',
    name: 'Nguyễn Văn C',
    gender: 'male',
    birthDate: '1970-05-20',
    deathDate: '',
    occupation: 'Giáo viên',
    bio: '',
    photo: '',
    parentIds: ['m1', 'm2'],
    spouseIds: ['m4'],
  },
  {
    id: 'm4',
    name: 'Lê Thị D',
    gender: 'female',
    birthDate: '1972-08-15',
    deathDate: '',
    occupation: '',
    bio: '',
    photo: '',
    parentIds: [],
    spouseIds: ['m3'],
  },
  {
    id: 'm5',
    name: 'Nguyễn Văn E',
    gender: 'male',
    birthDate: '1995-11-02',
    deathDate: '',
    occupation: 'Kỹ sư',
    bio: '',
    photo: '',
    parentIds: ['m3', 'm4'],
    spouseIds: [],
  },
]
